instance_groups:
- &opensearch-ingestor-config
  name: ingestor_opensearch_s3_1
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes:
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    properties:
      opensearch:
        heap_size: 1G
        http_host: 127.0.0.1
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
  - name: ingestor_syslog
    consumes:
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    properties:
      logstash:
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
        queue:
          max_bytes: 40gb
      logstash_ingestor:
        ingest_syslog_enabled: false
        health:
          disable_post_start: true
        syslog_tls:
          port: 6972
          ssl_cert: ((ingestor_syslog_server_tls.certificate))
          ssl_key: ((ingestor_syslog_server_tls.private_key))
      logstash_parser:
        inputs:
        - plugin: s3
          options:
            bucket: (( grab terraform_outputs.logs_opensearch_archive_bucket_name ))
            region: (( grab terraform_outputs.vpc_region ))
            type: syslog
        deployment_dictionary:
        - /var/vcap/packages/base-logstash-filters/deployment_lookup.yml
        - /var/vcap/jobs/deployment_lookup_config/config/deployment_lookup.yml
        filters:
        - logs-for-cf: /var/vcap/packages/cf-logstash-filters/logstash-filters-default.conf
        opensearch:
          data_hosts:
          - localhost
          index: "logs-app-%{+YYYY.MM.dd}"
          index_type: '%{@type}'
          ssl:
            ca: ((opensearch_node.ca))
            certificate: ((logstash.certificate))
            private_key: ((logstash.private_key))
    provides:
      ingestor:
        as: ingestor_link
    release: opensearch
  - name: deployment_lookup_config
    release: opensearch
  vm_type: r6i.xlarge.logsearch.ingestor
  networks:
  - name: services
  persistent_disk_type: logs_opensearch_ingestor
  stemcell: default
  azs:
  - z1
  vm_extensions:
  - logs-opensearch-ingestor-profile

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_2

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_3

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_4

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_5

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_6

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_7

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_8

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_9

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_10

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_11

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_12

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_13

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_14

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_15

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_16

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_17
  instances: 0

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_18
  instances: 0

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_19
  instances: 0

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_20
  instances: 0

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_21
  instances: 0

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_22
  instances: 0

- <<: *opensearch-ingestor-config
  name: ingestor_opensearch_s3_23
  instances: 0